"""
SunoAPI music-generation toolset
"""
import logging
import re
from typing import List, Optional, TYPE_CHECKING, Annotated, Any
from pydantic import BaseModel, Field, SkipValidation
from pydantic.json_schema import SkipJsonSchema
from app.tools.runtime import tool
from app.tools.runtime import ToolRuntime

if TYPE_CHECKING:
    from ...services.tool_service import ToolInfo

from ...llm.suno_service import get_suno_service, SunoService
from ...models.image_result import MusicGenerationResult, MusicProvider
from ...models.tool_enums import ToolName
from ...services.account.account_router import get_account_router

logger = logging.getLogger(__name__)

_STRUCTURED_LYRIC_TAG = re.compile(
    r"(?im)^\s*\[(?:intro|verse|pre-chorus|chorus|hook|refrain|bridge|outro|end)\b[^\]]*\]"
)


def _normalize_lyric_mode(
    prompt: str,
    *,
    has_lyrics: bool,
    auto_lyrics: bool,
) -> tuple[bool, bool]:
    """Prevent a music description from being submitted as literal lyrics.

    `has_lyrics` means the prompt already contains structured lyrics. When the
    planner selects it for an ordinary description, fall back to auto-lyrics.
    Explicit structured lyrics always win over the mutually exclusive
    auto-lyrics flag.
    """
    structured = bool(_STRUCTURED_LYRIC_TAG.search(prompt or ""))
    if has_lyrics and structured:
        if auto_lyrics:
            logger.warning(
                "Both has_lyrics and auto_lyrics were set; structured lyrics take precedence"
            )
        return True, False
    if has_lyrics:
        logger.warning(
            "has_lyrics was set without structured lyric sections; normalizing to auto_lyrics"
        )
        return False, True
    return False, bool(auto_lyrics)


class SunoMusicInput(BaseModel):
    """Input schema for Suno music generation."""
    prompt: str = Field(
        description="音乐生成提示词。has_lyrics=False时为英文音乐描述（最多400字符），has_lyrics=True时为结构化歌词（需包含[Verse], [Chorus]等标签，最多5000字符）"
    )
    has_lyrics: bool = Field(
        default=False,
        description="是否包含歌词。True=生成带歌词的歌曲（prompt 为歌词文本）；False=纯音乐BGM 或 auto_lyrics 模式"
    )
    auto_lyrics: bool = Field(
        default=False,
        description="是否根据描述自动生成带人声歌曲（歌词由 Suno 生成）。仅当 has_lyrics=False 时有效；True=描述→带人声歌曲，False=纯器乐BGM"
    )
    target_duration: Optional[int] = Field(
        default=None,
        description="目标时长（秒）；有歌词或 auto_lyrics 时传入。Suno 多版本按返回顺序采用，服务端不按时长重排或二次生成"
    )
    tags: Optional[str] = Field(
        default=None,
        description="歌曲风格标签（可选），如 'Fast 160BPM, Brief, Short version'。v4及以下最多200字符，v4.5及以上最多1000字符"
    )
    vocal_gender: Optional[str] = Field(
        default=None,
        description="人声性别（可选，仅 v4-5+）：'f' 女声，'m' 男声。从用户描述或参考图片推断；推断不出则不传"
    )
    runtime: Annotated[Any, SkipValidation, SkipJsonSchema()] = Field(
        default=None,
        description="Provider runtime context (internal use only)"
    )


async def _generate_music_with_suno_impl(
    prompt: str,
    has_lyrics: bool = False,
    auto_lyrics: bool = False,
    target_duration: Optional[int] = None,
    tags: Optional[str] = None,
    vocal_gender: Optional[str] = None,
    mv: Optional[str] = None,
) -> MusicGenerationResult:
    """SunoAPI music-generation implementation - core logic."""
    try:
        has_lyrics, auto_lyrics = _normalize_lyric_mode(
            prompt,
            has_lyrics=has_lyrics,
            auto_lyrics=auto_lyrics,
        )
        logger.info(f"🎵 SunoAPI音乐生成开始")
        logger.info(
            "🎵 工具入参: has_lyrics=%s auto_lyrics=%s target_duration=%s vocal_gender=%r tags=%r prompt_len=%s prompt_head=%r",
            has_lyrics,
            auto_lyrics,
            target_duration,
            vocal_gender,
            tags,
            len(prompt or ""),
            (prompt or "")[:240],
        )

        # three modes: user lyrics | auto lyrics (description -> with vocals) | pure BGM
        if has_lyrics:
            # with lyrics: custom_mode=True, make_instrumental=False
            # Custom mode: up to 5000 characters
            custom_mode = True
            make_instrumental = False
            lyrics = prompt[:5000]  # truncate to the first 5000 characters
            gpt_prompt = None
            if len(prompt) > 5000:
                logger.warning(f"🎵 歌词过长，截取前5000字符")
            logger.info(f"🎵 模式: Custom（带歌词，mv={mv or 'chirp-v4-5'}）")
            logger.info(f"🎵 结构化歌词: {lyrics[:100]}...")
            if tags:
                logger.info(f"🎵 风格标签: {tags}")
        elif auto_lyrics:
            # description -> with vocals: custom_mode=False, make_instrumental=False, lyrics auto-generated by Suno
            custom_mode = False
            make_instrumental = False
            lyrics = None
            gpt_prompt = prompt[:400]  # truncate to the first 400 characters
            if len(prompt) > 400:
                logger.warning(f"🎵 描述过长，截取前400字符")
            logger.info(f"🎵 模式: GPT + 带人声（auto lyrics）")
            logger.info(f"🎵 音乐描述: {gpt_prompt[:100]}...")
        else:
            # no lyrics and not auto_lyrics: custom_mode=False, make_instrumental=True
            # GPT-mode pure music: up to 400 characters
            custom_mode = False
            make_instrumental = True
            lyrics = None
            gpt_prompt = prompt[:400]  # truncate to the first 400 characters
            if len(prompt) > 400:
                logger.warning(f"🎵 描述过长，截取前400字符")
            logger.info(f"🎵 模式: GPT（纯音乐BGM）")
            logger.info(f"🎵 音乐描述: {gpt_prompt[:100]}...")

        # define the actual request function (takes api_key as the first parameter)
        async def _make_suno_request(api_key: str):
            """The actual Suno API call."""
            suno_service = SunoService(api_key=api_key)

            # pack the generation parameters (for duration selection etc. in the poll phase)
            generation_params = {
                "has_lyrics": has_lyrics,
                "auto_lyrics": auto_lyrics,
                "target_duration": target_duration,
                "prompt": prompt,
                "custom_mode": custom_mode,
                "make_instrumental": make_instrumental,
                "tags": tags,
                "vocal_gender": vocal_gender
            }
            _vocal = vocal_gender if vocal_gender in ("f", "m") else None
            return await suno_service.generate_music(
                prompt=gpt_prompt,
                custom_mode=custom_mode,
                make_instrumental=make_instrumental,
                lyrics=lyrics,
                mv=mv or "chirp-v4-5",
                tags=tags,
                vocal_gender=_vocal,
                duration=target_duration,
                generation_params=generation_params
            )

        # use the account router
        from ...models.tool_enums import ToolProvider, ToolType
        router = await get_account_router()
        result = await router.route_tool_request(
            provider=ToolProvider.SUNO,
            tool_type=ToolType.CHIRP_V4_5,
            request_func=_make_suno_request
        )

        if result.success:
            # ⭐ Sanity check: Suno occasionally has "success=True but empty clips / empty audio_url" false positives
            # common trigger: server 500 + very short clip (5s/10s); SunoService treats the 500 as acceptable and still sets success=True
            # trusting result.success alone would give downstream a "successful" music version with no audio, so the actual audio_url must be authoritative
            valid_clips = [
                c for c in (result.clips or [])
                if (getattr(c, "audio_url", "") or "").strip()
            ]
            if not valid_clips:
                empty_reason = (
                    "no clips returned"
                    if not result.clips
                    else f"all {len(result.clips)} clips have empty audio_url"
                )
                err_msg = f"SunoAPI 返回 success=True 但实际 {empty_reason}（疑似服务端 500 假阳性）"
                logger.error(
                    f"❌ {err_msg}  task_id={result.task_id} message={result.message!r}"
                )
                return MusicGenerationResult.error_result(
                    error_message=err_msg,
                    provider=MusicProvider.SUNO,
                    task_id=result.task_id,
                )

            # when some clips have no audio_url, drop the empty clips and keep the valid ones
            if len(valid_clips) != len(result.clips):
                dropped = len(result.clips) - len(valid_clips)
                logger.warning(
                    f"⚠️ Suno 返回 {len(result.clips)} 个 clips 中 {dropped} 个 audio_url 为空，已剔除"
                )
                result = result.model_copy(
                    update={"clips": valid_clips, "clips_count": len(valid_clips)}
                )

            audio_url = valid_clips[0].audio_url
            logger.info(f"✅ SunoAPI音乐生成成功: {audio_url}")

            # ⭐ compute cost (using the unified calculate_cost method)
            from ...services.tool_service import ToolService
            from ...models.tool_enums import ToolType
            cost = ToolService.calculate_cost(ToolType.CHIRP_V4_5)
            if cost > 0:
                ToolService.log_cost(cost)
                logger.info(f"💰 Suno 音乐生成成本: ${cost:.6f}")
                cb = ToolService.get_credit_callback()
                if cb:
                    cb.add_tool_cost(cost, tool_name=ToolName.SUNO.value, tool_type=ToolType.CHIRP_V4_5)
            result = result.model_copy(update={"billing_cost": cost})
        else:
            logger.error(f"❌ SunoAPI音乐生成失败: {result.error}")

        return result

    except Exception as e:
        result = MusicGenerationResult.error_result(
            error_message=f"SunoAPI音乐生成异常: {str(e)}",
            provider=MusicProvider.SUNO
        )
        logger.error(f"❌ SunoAPI音乐生成异常: {str(e)}")
        return result


@tool(ToolName.SUNO, args_schema=SunoMusicInput)
async def generate_music_with_suno(
    prompt: str,
    has_lyrics: bool = False,
    auto_lyrics: bool = False,
    target_duration: Optional[int] = None,
    tags: Optional[str] = None,
    vocal_gender: Optional[str] = None,
    runtime: ToolRuntime[Any] = None
) -> MusicGenerationResult:
    """Professional SunoAPI AI music-generation tool (uses the chirp-v4-5 model).

    🎵 **Automatically decides the generation mode from user input**:
    - has_lyrics=False -> generate pure instrumental BGM (prompt is an English music description, up to 400 chars)
    - has_lyrics=True -> generate a song with lyrics (prompt is structured lyrics, up to 5000 chars)

    🎯 **Parameters**:
    - prompt: music-generation prompt
      * has_lyrics=False: English music description (e.g. "A calm piano melody", up to 400 chars)
      * has_lyrics=True: structured lyrics (must include [Verse], [Chorus], etc. tags, up to 5000 chars)
    - has_lyrics: whether to include lyrics (True=song, False=pure BGM), default False
    - target_duration: target duration (seconds), for duration control when there are lyrics. Suno generates 2 versions; the server uses them in return order, without regenerating or reordering for duration deviation
    - tags: song style tags (optional), e.g. "Fast 160BPM, Brief, Short version"
    - vocal_gender: vocal gender (optional, only for v4-5+ with vocals): 'f' female, 'm' male. Inferred from the user description or reference image; omitted if it cannot be inferred
      * v4 and below: up to 200 chars
      * v4.5 and above: up to 1000 chars
      * used to control rhythm, style, duration, etc.

    🎼 **Lyric structure tags** (used when has_lyrics=True):
    - [Intro] - intro
    - [Verse] - verse
    - [Chorus] - chorus
    - [Bridge] - bridge
    - [Outro] - outro

    ⚠️ **Character limits**:
    - pure BGM (has_lyrics=False): prompt up to 400 chars
    - song with lyrics (has_lyrics=True): prompt up to 5000 chars
    - anything beyond is automatically truncated

    ⏱️ **Duration** (when has_lyrics=True or auto_lyrics=True and target_duration is passed):
    - Suno may return multiple versions; they are used in API return order, without calling the tool again for deviation from target_duration

    📋 **Model used**: chirp-v4-5

    💰 **Cost**: $0.08 per song

    Returns: a MusicGenerationResult object
    """
    return await _generate_music_with_suno_impl(
        prompt=prompt,
        has_lyrics=has_lyrics,
        auto_lyrics=auto_lyrics,
        target_duration=target_duration,
        tags=tags,
        vocal_gender=vocal_gender
    )


def get_suno_tools() -> List['ToolInfo']:
    """Get the SunoAPI tool info list.

    Returns:
        List[ToolInfo]: tool info list
    """
    from ...models.tool_enums import ToolType, ToolProvider, ToolCategory
    from ...services.tool_service import ToolInfo

    tool_type = ToolType.CHIRP_V4_5
    provider = ToolProvider.SUNO

    # create the tool's ToolInfo
    tool_info = ToolInfo(
        tool=generate_music_with_suno,
        tool_name=generate_music_with_suno.name,
        tool_type=tool_type,
        provider=provider,
        category=ToolCategory.MUSIC_GENERATION,
        mode=None
    )

    # ✅ add metadata to the tool object (so the callback can precisely obtain ToolType)
    try:
        if hasattr(tool_info.tool, 'metadata'):
            if tool_info.tool.metadata is None:
                tool_info.tool.metadata = {}
            tool_info.tool.metadata.update({
                "tool_type": tool_type.value,
                "provider": provider.value,
                "category": ToolCategory.MUSIC_GENERATION.value
            })
    except Exception as e:
        logger.warning(f"添加tool metadata失败: {e}")

    return [tool_info]


